### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by hanghoo** [ChuanyuXue/udp-latency#4]
Hi @ChuanyuXue, a quick question is what is the reason we choose socket instead of scapy to implement the udp latency? Thank you very much for your answering.

**Comment by ChuanyuXue** [comment]
The primary reason is simplicity. I have more familiarity with the socket library 😄

My goal was a straightforward script that's easy to understand and use. No special performance/accuracy consideration here.

**Comment by hanghoo** [comment]
Hi @ChuanyuXue, thanks for your answering. That's very helpful.
